ruby_version: 3.1
ignore:
  - 'spec/**/*':
    - Lint/ConstantDefinitionInBlock
    - Style/GlobalVars
  - 'lib/zip_kit/rack_body.rb': # Erroneous detection
    - Lint/OrderedMagicComments
    - Layout/EmptyLineAfterMagicComment